import type { Metadata } from "next";
import { Inter, Roboto, Rubik } from "next/font/google";
import "flag-icons/css/flag-icons.min.css";
import "./globals.css";
import { ThemeProvider } from "@/components/layouts/ThemeProvider";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin", "vietnamese"],
  variable: "--font-roboto",
});
const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "BuiVietAnh - Resume",
  description: "Generated by Vanhyoyo",
};

export default function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  return <LocaleDocument params={params}>{children}</LocaleDocument>;
}

async function LocaleDocument({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${inter.className} ${roboto.variable} ${rubik.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
